apiVersion: v1
kind: Secret
metadata:
  name: game-secrets
  namespace: game-server
type: Opaque
data:
  # 注意: 这些是base64编码的值，请使用以下命令创建Secret:
  # kubectl create secret generic game-secrets --from-literal=mysql-root-password=<password> --from-literal=redis-password=<password> --from-literal=nacos-mysql-password=<password> --from-literal=grafana-password=<password> -n game-server
  # 或者使用 kubectl create secret generic game-secrets --from-file=./secret.yaml -n game-server
  # ⚠️ 安全提示: 不要将包含真实密码的secret.yaml提交到版本控制系统
  mysql-root-password: cm9vdHBhc3N3b3Jk
  redis-password: YmluMjUyNTc3NQ==
  nacos-mysql-password: cm9vdHBhc3N3b3Jk
  grafana-password: YmluMjUyNTc3NQ==
